version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env
    ports:
      - "5500:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - vectorstore
    # Enable live code reload by mounting source directories if desired
    volumes:
      - ./server:/app/server
      - ./ai_agents:/app/ai_agents
      - ./storage:/app/storage

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend

  vectorstore:
    image: chromadb/chroma:0.4.24
    # Expose ChromaDB port for external tooling if required
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chromadb

volumes:
  chroma_data:
    # Named volume stores vector database files
    driver: local
