version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    env_file:
      - .env
    ports:
      - "5500:5000"
    environment:
      FLASK_ENV: development
    depends_on:
      - vectorstore
    volumes:
      - ./server:/app/server
      - ./ai_agents:/app/ai_agents
      - ./storage:/app/storage
    networks:
      - app_network

  frontend:
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    volumes:
      - ../frontend:/app
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app_network

  vectorstore:
    image: chromadb/chroma:0.4.24
    ports:
      - "8000:8000"
    volumes:
      - chroma_data:/chroma/.chromadb
    networks:
      - app_network

volumes:
  chroma_data:
    driver: local

networks:
  app_network:
    driver: bridge
