name: CI / build-and-test

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # ---------- Python backend ----------
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install backend deps
        run: pip install -r requirements.txt

      - name: Run backend tests (pytest)
        env:
          FLASK_ENV: test
        run: pytest -q server/tests

      # ---------- Node frontend ----------
      - name: Set up Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install frontend deps
        working-directory: client
        run: |
          if [ -f package-lock.json ]; then
            npm ci --no-audit --no-fund
          else
            npm install --no-audit --no-fund
          fi

      - name: Build frontend
        working-directory: client
        run: npm run build --if-present

      - name: Upload frontend build artifact
        if: success() && hashFiles('client/build/**/*') != ''
        uses: actions/upload-artifact@v4
        with:
          name: client-build
          path: client/build
